# Generated by Django 2.2 on 2019-09-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='title',
        ),
    ]
