# Generated by Django 2.2 on 2019-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='A',
            field=models.CharField(max_length=50, null=True, verbose_name='选项A'),
        ),
        migrations.AlterField(
            model_name='title',
            name='B',
            field=models.CharField(max_length=50, null=True, verbose_name='选项B'),
        ),
        migrations.AlterField(
            model_name='title',
            name='C',
            field=models.CharField(max_length=50, null=True, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='title',
            name='D',
            field=models.CharField(max_length=50, null=True, verbose_name='选项D'),
        ),
    ]
