# Generated by Django 2.2 on 2019-09-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190917_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psn', models.CharField(max_length=10, verbose_name='工号')),
                ('title', models.CharField(max_length=200, verbose_name='题目')),
                ('answer', models.CharField(max_length=50, verbose_name='答案')),
                ('score', models.CharField(max_length=5, verbose_name='得分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=200, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(max_length=10, verbose_name='类型（1：单选2：填空3：判断）'),
        ),
    ]
