# Generated by Django 2.2 on 2019-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190917_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(max_length=20, verbose_name='题目ID')),
                ('psn', models.CharField(max_length=10, verbose_name='工号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
