# Generated by Django 2.2 on 2019-09-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_zzuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='zzuser',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='zzuser',
            name='psn',
            field=models.CharField(max_length=10, unique=True, verbose_name='工号'),
        ),
    ]
