# Generated by Django 2.2 on 2019-09-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20190918_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='type',
            new_name='title_type',
        ),
    ]
