# Generated by Django 2.2 on 2019-09-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20190918_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='title_name',
        ),
    ]
