# Generated by Django 2.2 on 2019-09-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20190918_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='title',
            new_name='title_name',
        ),
    ]
